version: '3.8'

services:
  backend:
    build:
      context: ./backend
    restart: always
    environment:
      - PORT=3005
      - IMAP_HOST=mail.softigo.com
      - IMAP_PORT=993
      - IMAP_SECURE=true
      - ENCRYPTION_KEY=Nerzen_Bilisim_Sistemleri_2026_Key_32
    ports:
      - "3005:3005"
    networks:
      - softigo-network

  frontend:
    build:
      context: ./frontend
      args:
        - NEXT_PUBLIC_API_URL=http://email.softigo.com.tr:3005
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - softigo-network

networks:
  softigo-network:
    driver: bridge
